version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: fitness_postgres
    environment:
      POSTGRES_USER: fitness_user
      POSTGRES_PASSWORD: fitness_password
      POSTGRES_DB: fitness_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fitness_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fitness_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fitness.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - fitness_network

volumes:
  postgres_data:

networks:
  fitness_network:
    driver: bridge
